### ISSUE TITLE
Opening in new window

### ISSUE THREAD

**Issue by amserhii11** [nvh95/react-linkedin-login-oauth2#40]
Hi! Is it possible to open LinkedIn as PopUp or as Iframe? Because now it opens new tab. I expected it like a pop up, but it works incorrectly. Can you please explain it for me? 
![image](https://user-images.githubusercontent.com/27774005/114869281-792ac700-9dff-11eb-870e-0318f4a416f1.png)
![image](https://user-images.githubusercontent.com/27774005/114869323-82b42f00-9dff-11eb-8b79-cb245a05b115.png)

**Comment by amserhii11** [comment]
@nvh95

**Comment by amserhii11** [comment]
I mean, how to open in new window, not in tab.

**Comment by nvh95** [comment]
@amserhii11 It's using `window.open` API to open a new window/ tab. However, for example, if you are opening your browser in full screen mode on macOS, clicking the button will open a new tab instead of window. Otherwise, it will open a new window
![Oct-30-2021 12-02-36](https://user-images.githubusercontent.com/8603085/139520887-22d38629-a331-47ac-8770-cd4e7751e464.gif)

**Comment by nvh95** [comment]
I'm closing this issue now. Please feel free to discuss if the problem still persists
