### ISSUE TITLE
Client Credential Flow (2-legged OAuth)

### ISSUE THREAD

**Issue by karanattriCaw** [nvh95/react-linkedin-login-oauth2#44]
In the library default behaviour is Authorization Code Flow (3-legged OAuth) is there a way we can switch to Client credential flow (2-legged OAuth) where we can get access token ?

**Comment by nvh95** [comment]
@karanattriCaw I'm so sorry this library does not support Client Credential Flow (because this flow does not require to access any member-specific information) Please make a request directly via `https://www.linkedin.com/oauth/v2/accessToken`
Reference: https://docs.microsoft.com/en-us/linkedin/shared/authentication/client-credentials-flow
![image](https://user-images.githubusercontent.com/8603085/139518788-96c6a57f-e735-42cc-9306-4964eaa92a8a.png)
